### ISSUE TITLE
filtered views not exported ?

### ISSUE THREAD

**Issue by jbrunet** [structurizr/cli#54]
Hello, filtered views are not exported by structurizr cli. Is it on purpose or do you plan to have this feature ?

**Comment by simonbrowndotje** [comment]
When using filtered views with the Structurizr renderer, the filtered views use the layout information from the base view, so that the same element is always shown in the same place. With the export formats (e.g. PlantUML), this isn't possible, so filtered views are not exported. Unless you have a specific reason to use an export format, I'd recommend using the Structurizr renderer (e.g. via the free Structurizr Lite).
